name: dev-check-repository

on: [push]

jobs:
  build-node-test:
    runs-on: ubuntu-latest

    container:
      image: opendigitaleducation/node:18-alpine-pnpm
      options: --user root -v ${{ github.workspace }}:/home/node/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run pnpm install
        working-directory: ./frontend
        run: pnpm install
      - name: Check Quality Code
        working-directory: ./frontend
        run: pnpm run format:check && pnpm run lint
      - name: Run Build Vite
        working-directory: ./frontend
        run: pnpm build
      - name: Run tests
        working-directory: ./frontend
        run: pnpm test
      - name: Run npm install
        working-directory: ./angularJS
        run: yarn install
      - name: Run build node with Gulp
        working-directory: ./angularJS
        run: node_modules/gulp/bin/gulp.js build
      - name: Run test
        working-directory: ./angularJS
        run: yarn test

  build-gradle-test:
    runs-on: ubuntu-latest

    container:
      image: gradle:4.5-alpine
      options: --user root -v ${{ github.workspace }}:/home/gradle/:rw

    steps:
      - uses: actions/checkout@v1
      - name: Run build gradle
        working-directory: ./backend
        run: gradle assemble -g gradle-user-home
      - name: Run gradle test
        working-directory: ./backend
        run: gradle test  -g gradle-user-home --no-build-cache --rerun-tasks